In [22]:
import pandas as pd

In [23]:
df = pd.read_csv('../data/vendas.csv')
df.head()

,id_venda,data,produto,categoria,quantidade,preco_unitario,cidade
0,1,2026-01-05,Notebook,Informática,2,3500,Aracaju
1,2,2026-01-06,Mouse,Informática,5,80,Lagarto
2,3,2026-01-06,Teclado,Informática,3,150,Itabaiana
3,4,2026-01-07,Cadeira,Escritório,2,650,Aracaju
4,5,2026-01-07,Monitor,Informática,1,1200,Lagarto

In [24]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_venda        10 non-null     int64
 1   data            10 non-null     str
 2   produto         10 non-null     str
 3   categoria       10 non-null     str
 4   quantidade      10 non-null     int64
 5   preco_unitario  10 non-null     int64
 6   cidade          10 non-null     str
dtypes: int64(3), str(4)
memory usage: 692.0 bytes

In [25]:
df.describe()

       id_venda  quantidade  preco_unitario
count  10.00000   10.000000       10.000000
mean    5.50000    3.000000     1191.000000
std     3.02765    2.748737     1286.057282
min     1.00000    1.000000       80.000000
25%     3.25000    1.250000      275.000000
50%     5.50000    2.000000      775.000000
75%     7.75000    3.000000     1200.000000
max    10.00000   10.000000     3500.000000

In [26]:
df["valor_total"] = (
    df["quantidade"] *
    df["preco_unitario"]
)

In [27]:

df.head()

,id_venda,data,produto,categoria,quantidade,preco_unitario,cidade,valor_total
0,1,2026-01-05,Notebook,Informática,2,3500,Aracaju,7000
1,2,2026-01-06,Mouse,Informática,5,80,Lagarto,400
2,3,2026-01-06,Teclado,Informática,3,150,Itabaiana,450
3,4,2026-01-07,Cadeira,Escritório,2,650,Aracaju,1300
4,5,2026-01-07,Monitor,Informática,1,1200,Lagarto,1200

In [28]:
df["valor_total"].sum()

np.int64(20450)

In [29]:
df.groupby("cidade")["valor_total"].sum()

cidade
Aracaju      15400
Estância       900
Itabaiana     1750
Lagarto       2400
Name: valor_total, dtype: int64

In [30]:
df.groupby("categoria")["valor_total"].sum()

categoria
Escritório      3500
Informática    16950
Name: valor_total, dtype: int64

In [31]:
df.groupby("produto")["quantidade"].sum()

produto
Cadeira      4
Mesa         1
Monitor      4
Mouse       15
Notebook     3
Teclado      3
Name: quantidade, dtype: int64

In [32]:
df.groupby("produto")["quantidade"].sum().sort_values(
    ascending=False
    )

produto
Mouse       15
Cadeira      4
Monitor      4
Notebook     3
Teclado      3
Mesa         1
Name: quantidade, dtype: int64

In [34]:
import sqlite3

In [35]:
conn = sqlite3.connect('../data/vendas.db')

In [37]:
df.to_sql(
    "vendas",
    conn,
    if_exists="replace",
    index=False
)

10

In [38]:
query = """
SELECT *
FROM vendas
LIMIT 5
"""

pd.read_sql(query, conn)

,id_venda,data,produto,categoria,quantidade,preco_unitario,cidade,valor_total
0,1,2026-01-05,Notebook,Informática,2,3500,Aracaju,7000
1,2,2026-01-06,Mouse,Informática,5,80,Lagarto,400
2,3,2026-01-06,Teclado,Informática,3,150,Itabaiana,450
3,4,2026-01-07,Cadeira,Escritório,2,650,Aracaju,1300
4,5,2026-01-07,Monitor,Informática,1,1200,Lagarto,1200

In [39]:
query = """
SELECT
    cidade,
    SUM(valor_total) AS faturamento
FROM vendas
GROUP BY cidade
ORDER BY faturamento DESC
"""

pd.read_sql(query, conn)

      cidade  faturamento
0    Aracaju        15400
1    Lagarto         2400
2  Itabaiana         1750
3   Estância          900